### ISSUE TITLE
Publish different book sections on different web pages.

### ISSUE THREAD

**Issue by malteneuss** [NixOS/nix-book#29]
It would be good not do as the Nix manual does to publish everything on a single page. This makes content hard to index in search engines and therefore hard to find.

(Feel free to delete this issue if it's not the right place for suggestions)

**Comment by fricklerhandwerk** [comment]
Thanks for noting. We [decided to continue work on nix.dev](https://github.com/NixOS/nix-book/issues/11#issuecomment-1177939217), which is already paged (and can be even more granular in my opinion).
