### ISSUE TITLE
Status of the repository?

### ISSUE THREAD

**Issue by thufschmitt** [NixOS/nix-book#31]
Hi,

As part of https://github.com/NixOS/teams-collaboration/issues/1, I am trying to clarify the status of the repositories under the NixOS organisation.

This repository seems to be unmaintained or obsolete, so it will be archived in a month.

If you think it warrants staying here or should be moved to another organization instead, please answer this issue.

**Comment by fricklerhandwerk** [comment]
This is ready to archive. It may still come back if the idea of having an official narrative book gets enough traction and resources, but until then the repo can stay in the closet.

**Comment by 06kellyjac** [comment]
Will there be a catalog documenting what each repo is/was for, and maybe why it was archived?

**Comment by fricklerhandwerk** [comment]
This can (and IMO should) be written into the repo description. @thufschmitt is org an owner and can do that before pressing the button.

**Comment by thufschmitt** [comment]
Archiving the repo as indicated. Please comment on https://github.com/NixOS/teams-collaboration/issues/1 if this is a mistake.
