### ISSUE TITLE
Emacs org mode support

### ISSUE THREAD

**Issue by drishal** [NixOS/nix-book#6]
any plans to add support for Emacs org mode? :)

**Comment by fricklerhandwerk** [comment]
@drishal What would you imagine that to look like?

I would like to make it as easy as possible to contribute to this for anyone, especially Nix beginners, who often fall into the category of being novice to many other systems. So the question is how we could maintain a single source of truth while simultaneously have different interfaces to it, which are most convenient to different groups of people. I want to keep the amount of code around the contents as small as possible, as it just adds learning overhead for contributors and builds up maintenance burden.

Very open to suggestions how to strictly improve accessibility while maintaining all the other properties!

**Comment by drishal** [comment]
i could actually attempt to port the current repository to org files.
I assume the nix-book would be entirely written in markdown right?

**Comment by fricklerhandwerk** [comment]
Yes, markdown as long as possible; keep the barrier to entry as low as we reasonably can.

**Comment by 06kellyjac** [comment]
As much as I like org-mode its mostly limited to Emacs.

There's way way way more usage of markdown and various tools for writing it and producing it into websites/books

**Comment by drishal** [comment]
I now realize for this kind of resource it makes more sense to have a more portable format like markdown
closing this for now. But incase if anyone else has more time can try porting over to org mode :)
